services:
  dev_app:
    ports:
      - "9696:9696"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 500
    command: npm run start:dev
