services:
  postgres:
    image: postgres:15
    container_name: dict_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dict_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: dict_redis
    restart: always
    ports:
      - "6379:6379"

  dev_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dict_dev_app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_NAME: dict_db
      REDIS_HOST: redis

volumes:
  postgres_data:
